-- TSS_ACTOS; [C_Articulo]; [C_Preposicion];
create table parametricas.par_tipos_actos
(
	id integer generated by default as identity
		constraint par_tipos_actos_pkey
			primary key,
	descripcion varchar(200) not null,
	id_preposicion integer not null
		constraint "FK_tipos_actos_preposicion"
			references parametricas.par_tipos_preposicion,
	activo smallint default 1 not null,
	id_usuario_registra integer not null,
	fecha_registra timestamp with time zone not null,
	id_usuario_modifica integer,
	fecha_modifica timestamp with time zone,
	id_articulo integer not null
		constraint "FK_tipos_actos_articulo"
			references parametricas.par_tipos_articulos
);


