-- TSS_ACTOS; [C_Articulo]; [C_Preposicion];
create table parametricas.par_tipos_actos
(
	id integer generated by default as identity
		constraint par_tipos_actos_pkey
			primary key,
	descripcion varchar(200) not null,
	id_preposicion integer not null
		constraint "FK_tipos_actos_preposicion"
			references parametricas.par_tipos_preposicion,
	activo smallint default 1 not null,
	id_usuario_registra integer not null,
	fecha_registra timestamp with time zone not null,
	id_usuario_modifica integer,
	fecha_modifica timestamp with time zone,
	id_articulo integer not null
		constraint "FK_tipos_actos_articulo"
			references parametricas.par_tipos_articulos
);

comment on table parametricas.par_tipos_actos is 'Tabla que contiene los tipos de actos que se pueden impugnar ante la AIT';
comment on column parametricas.par_tipos_actos.id is 'Llave primaria de la tabla';
comment on column parametricas.par_tipos_actos.id_preposicion is 'Identificador de la preposición para la oración.';
comment on column parametricas.par_tipos_actos.activo is 'Indica si el registro estará activo en sistema 1=Activo 0= Inactivo';
comment on column parametricas.par_tipos_actos.id_usuario_registra is 'Identificador del usuario que realiza el registro';
comment on column parametricas.par_tipos_actos.fecha_registra is 'Fecha en la que se registra la información';
comment on column parametricas.par_tipos_actos.id_usuario_modifica is 'Identificador del usuario que realiza modificaciones en el registro';
comment on column parametricas.par_tipos_actos.fecha_modifica is 'Fecha en la que se realiza modificaciones a la información';
comment on column parametricas.par_tipos_actos.id_articulo is 'Identificador del artículo';

alter table parametricas.par_tipos_actos owner to postgres;

