-- [dbo].[TSS_FUNCIONARIOS]
-- seguridad.seg_personas
create table seguridad.seg_personas
(
  id integer generated by default as identity
    constraint seg_personas_pkey
      primary key,
  nombres varchar(100) not null,
  ap_paterno varchar(50) not null,
  ap_materno varchar(50),
  ci varchar(10),
  sexo smallint not null,
  telefono varchar(45),
  num_celular varchar(45),
  email varchar(50),
  fecha_nacimiento timestamp with time zone,
  zona_domicilio varchar(100),
  calle_domicilio varchar(100),
  numero_domicilio varchar(50),
  ruta_fotografia varchar(100),
  id_region integer
    constraint fk_regiones_personas
      references seguridad.seg_regiones,
  id_cargo integer
    constraint fk_cargos_personas
      references seguridad.seg_cargos,
  id_usuario_registra integer not null,
  fecha_registra timestamp with time zone not null,
  id_usuario_modifica integer,
  fecha_modifica timestamp with time zone,
  activo smallint default 1 not null
);

TRUNCATE TABLE seguridad.seg_personas RESTART IDENTITY CASCADE;