-- [dbo].[TSS_FUNCIONARIOS]
-- seguridad.seg_personas
create table seguridad.seg_personas
(
  id integer generated by default as identity
    constraint seg_personas_pkey
      primary key,
  nombres varchar(100) not null,
  ap_paterno varchar(50) not null,
  ap_materno varchar(50),
  ci varchar(10),
  sexo smallint not null,
  telefono varchar(45),
  num_celular varchar(45),
  email varchar(50),
  fecha_nacimiento timestamp with time zone,
  zona_domicilio varchar(100),
  calle_domicilio varchar(100),
  numero_domicilio varchar(50),
  ruta_fotografia varchar(100),
  id_region integer
    constraint fk_regiones_personas
      references seguridad.seg_regiones,
  id_cargo integer
    constraint fk_cargos_personas
      references seguridad.seg_cargos,
  id_usuario_registra integer not null,
  fecha_registra timestamp with time zone not null,
  id_usuario_modifica integer,
  fecha_modifica timestamp with time zone,
  activo smallint default 1 not null
);
-- COMMENTS
comment on table seguridad.seg_personas is 'Tabla que almacena la información de las personas que podrán o no acceder al sistema.';
comment on column seguridad.seg_personas.id is 'Llave primaria de la tabla';
comment on column seguridad.seg_personas.nombres is 'Nombres de la persona';
comment on column seguridad.seg_personas.ap_paterno is 'Apellido paterno de la persona';
comment on column seguridad.seg_personas.ap_materno is 'Apellido materno de la persona';
comment on column seguridad.seg_personas.ci is 'Cédula de identidad de la persona';
comment on column seguridad.seg_personas.sexo is 'Sexo de la persona 1=Masculino 0=Femenino';
comment on column seguridad.seg_personas.telefono is 'Nümero(s) de teléfono(s) fijo(s) de la persona';
comment on column seguridad.seg_personas.num_celular is 'Nümero(s) de teléfono(s) celular(es) de la persona';
comment on column seguridad.seg_personas.email is 'COrreo electrónico de la persona';
comment on column seguridad.seg_personas.fecha_nacimiento is 'Fecha de nacimiento de la persona';
comment on column seguridad.seg_personas.zona_domicilio is 'Descripción de la zona donde vive la persona';
comment on column seguridad.seg_personas.calle_domicilio is 'Nombre de la calle donde vive la persona';
comment on column seguridad.seg_personas.numero_domicilio is 'Número del domicilio de la persona';
comment on column seguridad.seg_personas.ruta_fotografia is 'Ruta donde se almacena la fotografía de la persona';
comment on column seguridad.seg_personas.id_region is 'Identificador de la región donde vive la persona';
comment on column seguridad.seg_personas.id_cargo is 'Identificador del cargo de la persona';
comment on column seguridad.seg_personas.id_usuario_registra is 'Identificador del usuario que realiza el registro';
comment on column seguridad.seg_personas.fecha_registra is 'Fecha en la que se registra la información';
comment on column seguridad.seg_personas.id_usuario_modifica is 'Identificador del usuario que realiza modificaciones en el registro';
comment on column seguridad.seg_personas.fecha_modifica is 'Fecha en la que se realiza modificaciones a la información';
comment on column seguridad.seg_personas.activo is 'Estado del registro 1=Activo 0= Inactivo';
-- DDL
alter table seguridad.seg_personas owner to postgres;
